name: openapi_generator_sandbox
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  openapi_generator_annotations: ^5.0.2
  fake_rest_api:
    path: api/fake_rest_api
 

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  openapi_generator: ^5.0.2

